### ISSUE TITLE
JS Fiddle Embedded Result no longer working in url

### ISSUE THREAD

**Issue by 3dhavok** [jsfiddle/jsfiddle-issues#1577] opened 2020-05-06 17:39 UTC
JS Fiddle url links to mockup/prototype projects embedded result no longer works as it used to. It used to load everything in url, full width without jsFiddle interface, now it takes me to the split dev screens. This does not bode well for client reviews or sharing with non-technical types.

I used to be able to add on the end of my fiddle url `/embedded/result` and it would work as intended. This now takes you back to regular fiddle split screen. I tried `/embed/result` and that shows a page with javascript instead of the result page i need.

**Comment by greggman** [comment] 2020-05-07 05:53
I'm having the same issue. It used to be I could make a jsfiddle and test on mobile using /embedded/result but now it redirects to the non-mobile friendly editor instead of just showing the result with a header like it used to (you can see the old page for a moment before it redirects)

**Comment by oskarkrawczyk** [comment] 2020-05-07 13:39
Duplicate of https://github.com/jsfiddle/jsfiddle-issues/issues/1578

**Closed by oskarkrawczyk** 2020-05-07 13:39 UTC

**Comment by oskarkrawczyk** [comment] 2020-05-07 13:43
Please see my comment here, input would be appreciated in order to bring this back: https://github.com/jsfiddle/jsfiddle-issues/issues/1578#issuecomment-625263945
