### ISSUE TITLE
Add allowpaymentrequest to render iframe

### ISSUE THREAD

**Issue by athyuttamre** [jsfiddle/jsfiddle-issues#1099] opened 2017-11-21 00:55 UTC
The W3C Payment Request API is supported within iframes only if the `allowpaymentreqeust` property is set on the iframe. It would be useful to add this property to jsfiddle's render iframe so that we can test the API.

https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API

**Comment by oskarkrawczyk** [comment] 2017-11-21 22:02
@athyuttamre will do.

@majkelcc I've updated both apps to have this change, can you deploy?

**Comment by athyuttamre** [comment] 2017-11-22 06:59
Awesome, thanks so much @oskarkrawczyk!

**Comment by atty-stripe** [comment] 2018-01-03 01:31
Hi there! Looks like the latest release of JSFiddle shipped with a typo, and now the field says "allowpaymentreqeust" rather than "allowpaymentrequest". Could we fix this please?

**Comment by oskarkrawczyk** [comment] 2018-01-03 13:49
Regression. Will fix soon.

**Comment by oskarkrawczyk** [comment] 2018-01-03 13:52
Should be fixed.

**Closed by oskarkrawczyk** 2018-01-03 13:52 UTC

**Comment by atty-stripe** [comment] 2018-01-03 19:09
Awesome, thanks!

**Comment by atty-stripe** [comment] 2018-01-17 00:48
@oskarkrawczyk looks like the typo is back. Could you fix again please?

**Comment by oskarkrawczyk** [comment] 2018-01-18 14:37
@atty-stripe Dammit! Thanks for letting me know, fixed (again).

**Comment by oskarkrawczyk** [comment] 2018-01-18 14:39
@atty-stripe Are you guys using JSFiddle for checkout examples? Or just internally?

**Comment by athyuttamre** [comment] 2018-01-18 18:05
@oskarkrawczyk mostly internally for debugging and creating quick examples! Sometimes to help users debug their integrations as well.

**Comment by oskarkrawczyk** [comment] 2018-01-18 18:07
@athyuttamre gotcha, awesome to hear that!
