### ISSUE TITLE
update to my issue #1181

### ISSUE THREAD

**Issue by wayneker18** [jsfiddle/jsfiddle-issues#1187] opened 2018-02-23 08:55 UTC
i have found out what causes the issue i expressed in my original issue log

https://github.com/jsfiddle/jsfiddle-issues/issues/1181#issuecomment-367003920

in Firefox, when the zoom % for the browser in Firefox is less than 100% it occurs, if i move it back to 100% the issue goes. i tried this on Chome, and it doesnt have the same issue.

**Comment by oskarkrawczyk** [comment] 2018-02-23 19:51
Edge case, if you want to, please add this under the original issue, if anyone else prompts us about this, we'll have a look.

Closing since it's a duplicate of the original.

**Closed by oskarkrawczyk** 2018-02-23 19:51 UTC
