### ISSUE TITLE
jsFiddle does not allow deleting references

### ISSUE THREAD

**Issue by NickMitrokhin** [jsfiddle/jsfiddle-issues#914] opened 2016-10-24 19:40 UTC
Hello,

jsFiddle does not allow me to save changes when I delete a reference. Please take a look at [this](https://jsfiddle.net/gfeq59z5/1/) example. Try to delete dx.all.js and click "Update". After that, refresh the fiddle and you will see that dx.all.js is still there.

**Comment by oskarkrawczyk** [comment] 2016-10-24 21:13
Duplicate of #892

**Closed by oskarkrawczyk** 2016-10-24 21:13 UTC
