### ISSUE TITLE
Ajax request from Github works incorrectly 

### ISSUE THREAD

**Issue by zclimber** [jsfiddle/jsfiddle-issues#1350] opened 2018-08-05 19:16 UTC
When user name or repository name contains "tree", JSFiddle cannot fetch resource from Github.
For example, I tried to use file [https://github.com/zclimber/jstree-demo/tree/master/ajax-responses/2/demo.response.json](https://github.com/zclimber/jstree-demo/tree/master/ajax-responses/2/demo.response.json) for Ajax, and got 404 with following text:

> Repository/Gist not found: https://github.com/zclimber/jsraw-demo/tree/master/ajax-responses/2/demo.response.json"

Looks like you use a regex to change first occurence of "tree" to "raw". And suggested fix is to request files directly from [https://raw.githubusercontent.com](https://raw.githubusercontent.com).

**Comment by zclimber** [comment] 2018-08-05 19:29
Also, MIME type is wrong and is always "text/plain; charset=utf-8", verified on example from docs: [http://jsfiddle.net/caynsg58/1/](http://jsfiddle.net/caynsg58/1/).

**Comment by majkelcc** [comment] 2018-08-08 11:36
Hi @zclimber, thanks for reporting this bug. Both should be fixed. As to replacing `tree` with `raw`, we switched to searching for `/tree/` part to replace it with `/raw/` for now.

Do you know if it's safe to use `raw.githubusercontent.com` on sites like `jsfiddle`? We can consider a switch in the futute 😉

**Comment by zclimber** [comment] 2018-08-08 11:50
According to [this post](https://developer.github.com/changes/2014-04-25-user-content-security/), Github started to serve user content from subdomains of `githubusercontent.com` since 2014. So seems pretty safe to me.

**Comment by fedorareis** [comment] 2018-08-29 22:41
@zclimber The MIME type isn't a fixable issue as it is caused by the browser. Github serves the raw files with `X-Content-Type-Options: nosniff` to keep people from serving content from those files. You can read more about the behavior in [this chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=180007) the general workaround is to use [rawgit.com](https://rawgit.com/)

**Closed** 2018-12-03 23:21 UTC
Labels: wontfix
