### ISSUE TITLE
Syntax highlighting breaks when changing FRAMEWORKS & EXTENSIONS

### ISSUE THREAD

**Issue by MrUpsidown** [jsfiddle/jsfiddle-issues#1127] opened 2018-01-05 12:10 UTC
# Problem:

- When I change something in FRAMEWORKS & EXTENSIONS (for example, add jQuery, or even switch to No-Library (pure JS)), the JS syntax highlighting goes away.

# Info:

- Tested on macOS 10.13.2 with Chrome 63.0.3239.132 and Safari 11.0.2 (13604.4.7.1.3)

<img src="https://i.imgur.com/rp2nWsc.png">

**Comment by oskarkrawczyk** [comment] 2018-01-05 12:11
Thanks, fix is in the works.

**Comment by MrUpsidown** [comment] 2018-01-05 12:12
Perfect, thanks very much!

**Comment by charlietfl** [comment] 2018-01-14 10:07
There seems to be a regression if this was ever fixed.  Has been broken for many days now

**Comment by oskarkrawczyk** [comment] 2018-01-14 12:15
**Note to self:** Issue is most likely caused by lang+framework name passed to highlighter instead of just lang.

**Comment by oskarkrawczyk** [comment] 2018-01-15 14:07
Fixed!

**Closed by oskarkrawczyk** 2018-01-15 14:07 UTC
