### ISSUE TITLE
Unlisted Fiddles Are Listed

### ISSUE THREAD

**Issue by mighty-sparrow** [jsfiddle/jsfiddle-issues#1543] opened 2020-02-10 06:01 UTC
All fiddles are available for viewing on a user profile, regardless of whether or not it has a `Title`.

Typically a Fiddle is not known to other users (anonymous or otherwise), even though it is accessible by a direct link.

In the example below:

1. I created a user with the name _**Test Account**_ (i.e. `test_account`)
2. I created a single, _untitled_ Fiddle.
3. From another window, I used Incognito to browse the [`test_account`](https://jsfiddle.net/user/test_account/fiddles/)'s profile
4. The untitled Fiddle is visible on the user's profile

# Expected
No _Unlisted_ Fiddles will display on the user's page.

# Actual Result
A fiddle that should be unlisted/hidden is visible to anyone browsing the page.

## Screen Shots
![Screen Shot 2020-02-09 at 9 43 59 PM](https://user-images.githubusercontent.com/20146574/74124159-3b406c00-4b86-11ea-9dd6-721543be8f83.png)
![Screen Shot 2020-02-09 at 9 45 00 PM](https://user-images.githubusercontent.com/20146574/74124160-3d0a2f80-4b86-11ea-8cc5-8171f3ceb832.png)
![Screen Shot 2020-02-09 at 9 47 19 PM](https://user-images.githubusercontent.com/20146574/74124164-3e3b5c80-4b86-11ea-8f3a-11bdde070208.png)

## Worth noting...
I know this is a totally different feature, as specified in comments in issues like #1540, but it seems like a bad approach to release UI changes without any functionality behind them.  Basically, if there is no such thing as a _Public_ or _Private_ Fiddle, there is no reason to add _Public_ or _Private_ views on a user's _Your Fiddles_ page.

![Screen Shot 2020-02-09 at 9 48 30 PM](https://user-images.githubusercontent.com/20146574/74124165-3ed3f300-4b86-11ea-99b9-52ccfd41ff14.png)

**Comment by oskarkrawczyk** [comment] 2020-02-10 06:24
There's no such thing as **unlisted fiddles**.

**Private fiddles** will be introduced soon. That tab is there by mistake - will fix.

**Comment by mighty-sparrow** [comment] 2020-02-10 06:38
> There's no such thing as **unlisted fiddles**.

I've seen a similar response in other comments.  In fact, in [this comment](https://github.com/jsfiddle/jsfiddle-issues/issues/1519#issuecomment-573440191) you state the exact opposite.  I'm not sure why there is such obvious push back.

Symantics aside, I think it's clear why users are concerned and the exact anomaly they are trying to point out.  Please acknowledge you understand the change in functionality users are experiencing.  It's not that Fiddles were ever explicitly _private_, rather they were implicitly unavailable to random, anonymous users if that's what they chose.  The change in behavior (i.e. the resultant confusion) is a direct result of the UI changes pushed to production.

> **Private fiddles** will be introduced soon. That tab is there by mistake - will fix.

Where is this in the backlog; do you have an issue to reference?

**Comment by oskarkrawczyk** [comment] 2020-02-10 07:01
> I've seen a similar response in other comments. In fact, in this comment you state the exact opposite. I'm not sure why there is such obvious push back.

- "Untitled fiddles **were** never really private" 
- "In the newest update **both types of fiddles are listed** on the public profile".

> were implicitly unavailable to random

Any user could have access if he had the direct link, or if came from search results which were indexed by search engines.

True Private fiddles were on the roadmap for years, changing UI and how listings work is a part of that task.

**Comment by oskarkrawczyk** [comment] 2020-02-10 07:01
Closing. Duplicate of #1540

**Closed by oskarkrawczyk** 2020-02-10 07:01 UTC

**Comment by mighty-sparrow** [comment] 2020-02-14 04:40
# You're talking in circles, my friend.

ha, I mean...c'mon, man -- I have a ton of faith in your abilities and you **_know_** what people are writing about.

Your explanations are cyclical and obtuse, like just signed up and started using jsFiddle last week.

...it's a bit strange.
