### ISSUE TITLE
<script> version of embed shows result as empty if it is the starting tab

### ISSUE THREAD

**Issue by ryanpcmcquen** [jsfiddle/jsfiddle-issues#714] opened 2016-01-21 15:09 UTC
Clicking to another tab and back into 'Result' fixes it.

![screenshot-ryanpcmcquen neocities org 2016-01-21 07-08-41](https://cloud.githubusercontent.com/assets/772937/12484169/e396ff26-c00d-11e5-91d1-1ebf14010ea6.png)

**Comment by timroes** [comment] 2016-06-25 11:01
I saw a similar behavior: The result tab just doesn't seem to calculate any correct height, so it just keeps the height of the last tab, that was selected before. If you use `result` as first tab, this will lead to the height never set to anything else then 0.

**Comment by oskarkrawczyk** [comment] 2016-06-27 07:32
I've seen this issue a long time ago but fixed it, and since then this never happened in my tests.

Difficult to debug this issue.

**Comment by timroes** [comment] 2016-06-27 17:56
## Fiddle-ception

@oskarkrawczyk If you still cannot reproduce it, use this fiddle: https://jsfiddle.net/oqtrd3e3/ 

I just included the <script> tag of one of my other fiddles with the order result,html,css. As you can see (at least for me its reproducible) the result tab won't render with any high when you run the fiddle. But if you switch to another tab and back to the result tab again, it will render correctly.

Hope this helps you debug it.

**Comment by oskarkrawczyk** [comment] 2016-06-27 19:01
Thanks @timroes, I can in fact reproduce it now. Will try to fix it asap.

**Comment by oskarkrawczyk** [comment] 2016-12-13 13:22
Ok, turned out not to be such an easy fix as I thought. It's now fixed.

Thanks for the patience and reporting this issue!

**Closed by oskarkrawczyk** 2016-12-13 13:22 UTC
Labels: bug
