### ISSUE TITLE
JSFiddle Unusable in Chrome: Error causing editor to crash on load

### ISSUE THREAD

**Issue by WebWanderer2** [jsfiddle/jsfiddle-issues#723] opened 2016-02-12 13:46 UTC
An error in _dist-editor.js is causing the editor to crash on load in the Chrome Web browser, making JSFiddle currently unusable in this browser.

From Chrome console:

_Uncaught TypeError: Cannot read property 'code' of undefined
_Class.draftDiff_

![image](https://cloud.githubusercontent.com/assets/12719487/13008357/7abf5124-d15b-11e5-9574-f67c07e4332c.png)

This issue was found in Chrome Version 48.0.2564.109 m.
Tested in IE Version 11.0.9600.18205, Opera Version 35.0.2066.37, and Firefox Version 43.0.1 and are all working.

**Comment by WebWanderer2** [comment] 2016-02-12 13:57
It appears that editing an existing fiddle in chrome still works.

**Comment by oskarkrawczyk** [comment] 2016-02-12 14:01
No errors on our end.

Perhaps an extension that's breaking the site?

**Comment by WebWanderer2** [comment] 2016-02-12 14:16
I disabled each of my plugins and am still receiving the error. I'm still not sure why.

I also tried to "Relaunch Chrome in Windows 8 mode," and JSFiddle's editor still failed to load.

I am working from Windows 8.1.

**Comment by oskarkrawczyk** [comment] 2016-02-12 14:28
Don't have access to Windows, but I doubt it's an OS-related issue. I'll keep this ticket open for now and see if any one else reports this error.

**Comment by oskarkrawczyk** [comment] 2016-02-20 07:55
No similar reports has been issued. Closing.

**Comment by darrensw777** [comment] 2016-03-29 09:30
I have this issue too - Chrome Version 49.0.2623.110 m

Showing error in: https://jsfiddle.net/js/_dist-editor.js?update_17_03_2016_2

I have no extensions active. Windows 7 Home Premium

**Comment by WebWanderer2** [comment] 2016-03-29 17:37
I am still having this issue.

**Comment by oskarkrawczyk** [comment] 2016-03-29 17:39
Cannot replicate the issue = no fix.

**Comment by darrensw777** [comment] 2016-03-29 20:28
I get that - any idea what we can try to at least narrow things down?

**Comment by darrensw777** [comment] 2016-04-01 10:52
This is the line it fails on by the way:

`i = difflib.stringAsLines(n[this.options.name].code),`

**Comment by oskarkrawczyk** [comment] 2016-04-01 10:57
@darrensw777 if you go into your Local Storage and remove all objects related to JSFiddle. Can you confirm the issue disappears?

**Comment by darrensw777** [comment] 2016-04-01 11:05
Boom! Thanks for that - back to JSFiddle for me!

**Comment by oskarkrawczyk** [comment] 2016-04-01 11:07
Interesting issue. Will have a look if there's something obvious in the code not taken into account.

**Comment by oskarkrawczyk** [comment] 2016-04-01 12:48
The logic looks sound, added a few more checks here and there so we at least don't try get props of undefined objects.

**Closed by oskarkrawczyk** 2016-04-01 12:48 UTC

**Comment by oskarkrawczyk** [comment] 2016-04-01 13:00
@WebWanderer2 can you check if the issue is still present?

**Comment by WebWanderer2** [comment] 2016-04-01 14:25
It looks like I am fixed as well. Thanks guys, I really appreciate it!

**Comment by deladroid** [comment] 2016-04-07 17:12
I experienced the same thing, and oddly enough had finally created a new account, which after doing some fiddling edits, my account seemed to attach to someone else.  I had used "jasee" as a username, and it appeared to be connected to another user in Asia (I'm USA).  I switched my username, but I"m still having crash issues on a simple JSON fiddle.

**Comment by yozef** [comment] 2017-02-16 13:24
I'm having this same issue.
Steps to reproduce:
1- Use Chrome to go to https://jsfiddle.net/
2- Loads for at least 1 minute.
3- Oh-Snap alert from Chrome.
