### ISSUE TITLE
A fiddle cannot be selected for edit without invoking auto-run, even when said fiddle kills jsfiddle

### ISSUE THREAD

**Issue by craigphicks** [jsfiddle/jsfiddle-issues#1033] opened 2017-06-27 03:10 UTC
A fiddle cannot be selected for edit without invoking auto-run, even when said fiddle kills jsfiddle.
An avaricious fiddle, once running,  will freeze the screen (e.g. 100% CPU, voracious memory consumption).
I can't see anyway to abort the running fiddle, other than killing jsfiddle, which kills the editor too.
I want to edit the fiddle BEFORE running, obviously, to fix the fiddle's bug, but I don't see any "auto-run" option in "settings".
If there is no way to edit the fiddle before running, then I consider it a bug in the jsfiddle design.

**Comment by oskarkrawczyk** [comment] 2017-06-27 09:41
It's an edge case, only caused by incorrectly written code (infinite loops and such), JSFiddle can be hardly blamed for this, and even less the behavior can be marked as a bug since the edge case is user-generated.

There are no plans on not evaluating the fiddle once it loads.

A way around the edge case:

1. disable JS in browser
2. load fiddle
3. open up source code
4. find and copy code to a new fiddle (+ fixing the infinite loop issue, before saving)

**Closed by oskarkrawczyk** 2017-06-27 09:41 UTC

**Comment by craigphicks** [comment] 2017-06-27 22:00
Thank u Oscar for your detailed explanation and solution.
