### ISSUE TITLE
ctrl-shift-enter no longer enlarges the result window

### ISSUE THREAD

**Issue by cirixal** [jsfiddle/jsfiddle-issues#1413] opened 2019-01-15 16:32 UTC
Hello,

The keyboard command ctrl-shift-enter used to make a new tab with the results window expanded.  After the rollback on Friday that fixed the save/update and drafts error-this keyboard command seems to stop working. 

It's not a huge deal as the fiddle works fine with manual /embedded , just curious on why it stopped working. 

Thank you!

**Comment by oskarkrawczyk** [comment] 2019-01-15 16:53
I don't recall ever having such a shortcut, if it was working for you this way, it must have been some weird bug that has been fixed by unifying save/update actions.

**Closed by oskarkrawczyk** 2019-01-15 16:53 UTC

**Comment by MichaelXF** [comment] 2019-02-06 22:48
I used to do this all time? Especially with full-screen canvas fiddles this is definitely a bug I've been using it since summer 2018 and now it doesn't work

**Comment by oskarkrawczyk** [comment] 2019-02-07 07:40
Definitely not a bug since it's never been the intended behavior.
