### ISSUE TITLE
* in allow="microphone *; camera *" is still unsafe & unnecessary

### ISSUE THREAD

**Issue by jan-ivar** [jsfiddle/jsfiddle-issues#1571] opened 2020-04-20 18:46 UTC
From https://github.com/jsfiddle/jsfiddle-issues/issues/1557#issuecomment-612448492 for visibility:
> Hi @oskarkrawczyk did this get reverted?
> 
> I'm seeing `*` again e.g. in https://jsfiddle.net/jib1/zcuwfpnh/ I just created.
> ```js
> allow="midi *; geolocation *; microphone *; camera *; display-capture *; encrypted-media *"
> ```
>
> Is there a reason not to use the following (which should work in Safari as well)?
> ```js
> allow="midi; geolocation; microphone; camera; display-capture; encrypted-media"
> ```

**Comment by oskarkrawczyk** [comment] 2020-04-29 11:18
Duplicate of #1557. Closing. Please don't post same issues "for visibility".

**Closed by oskarkrawczyk** 2020-04-29 11:18 UTC
